[package]
name = "clockdate"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.24.0"
crossterm = "0.27.0"
chrono = "0.4"
ctrlc = "3"
figlet-rs = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
